platform: linux

image_resource:
  type: docker-image
  source:
      repository:  amazon/aws-cli
      tag: latest

inputs:
  - name: git-main

run:
  path: git-main/concourse/tasks/assert-state-bucket/assert_state_bucket.sh
