platform: linux

image_resource:
  type: docker-image
  source:
      repository:  ubuntu
      tag: latest

inputs:
  - name: git-main

run:
  path: git-main/concourse/tasks/deploy-tf/deploy_tf.sh
  args: [ "git-main" ]
